# Generated by Django 6.0.3 on 2026-04-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionactividad',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_actividad', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='participacionactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_actividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agendapersonal',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='unique_agenda_personal_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='participacionactividad',
            constraint=models.CheckConstraint(condition=models.Q(('persona__isnull', False), ('usuario__isnull', False), _connector='OR'), name='participacion_requiere_persona_o_usuario'),
        ),
    ]
