# Generated by Django 6.0.3 on 2026-04-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='agendapersonal',
            name='unique_agenda_personal_por_usuario',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='calendario',
        ),
        migrations.RemoveConstraint(
            model_name='participacionactividad',
            name='participacion_requiere_persona_o_usuario',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='es_global',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='titulo',
        ),
        migrations.AddField(
            model_name='actividad',
            name='dia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tema',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='actividadpersona',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_personas', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='actividadpersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='asistenciaactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='asistenciaactividad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_actividad', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='inscripcionactividad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_actividad', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='actividadpersona',
            name='rol_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividad_personas', to='actividades.rolactividad'),
        ),
        migrations.AddField(
            model_name='inscripcionactividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='actividades.tipoactividad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='actividades.tipoactividad'),
        ),
        migrations.RemoveField(
            model_name='agendapersonal',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.RemoveField(
            model_name='participacionactividad',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='participacionactividad',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='participacionactividad',
            name='usuario',
        ),
        migrations.AddConstraint(
            model_name='actividadpersona',
            constraint=models.UniqueConstraint(fields=('actividad', 'persona', 'rol_actividad'), name='unique_actividad_persona_rol'),
        ),
        migrations.AddConstraint(
            model_name='inscripcionactividad',
            constraint=models.UniqueConstraint(fields=('persona', 'tipo_actividad'), name='unique_inscripcion_persona_tipo_actividad'),
        ),
        migrations.DeleteModel(
            name='AgendaPersonal',
        ),
        migrations.DeleteModel(
            name='ParticipacionActividad',
        ),
    ]
