# Generated by Django 6.0.3 on 2026-04-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolsistema'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='personarol',
            name='unique_persona_rol',
        ),
        migrations.RemoveConstraint(
            model_name='personarol',
            name='unique_usuario_rol',
        ),
        migrations.RemoveConstraint(
            model_name='personarol',
            name='personarol_requiere_persona_o_usuario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='garante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='guia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='personas.tipodocumento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_persona', to='core.rolsistema'),
        ),
        migrations.DeleteModel(
            name='PersonaRol',
        ),
    ]
