# Generated by Django 6.0.3 on 2026-04-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='registrada_por',
        ),
        migrations.AddField(
            model_name='donacion',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemdonacion',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_donacion', to='donaciones.unidadmedida'),
        ),
    ]
