# Generated by Django 6.0.3 on 2026-04-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='comunicaciones.canalnotificacion')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
