# Generated by Django 6.0.3 on 2026-04-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='destinatario_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(condition=models.Q(('destinatario_persona__isnull', False), ('destinatario_usuario__isnull', False), _connector='OR'), name='notificacion_requiere_destinatario'),
        ),
    ]
