# Generated by Django 6.0.3 on 2026-04-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolsistema'),
        ('personas', '0002_tipodocumento_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.AlterModelOptions(
            name='registrocambio',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='registrocambio',
            name='datos_anteriores',
        ),
        migrations.RemoveField(
            model_name='registrocambio',
            name='datos_nuevos',
        ),
        migrations.RemoveField(
            model_name='registrocambio',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='registrocambio',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='registrocambio',
            name='objeto_id',
        ),
        migrations.RemoveField(
            model_name='registrocambio',
            name='realizado_por',
        ),
        migrations.AddField(
            model_name='registrocambio',
            name='entidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registrocambio',
            name='entidad_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registrocambio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registrocambio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrocambio',
            name='accion',
            field=models.CharField(choices=[('insercion', 'Insercion'), ('modificacion', 'Modificacion'), ('eliminacion', 'Eliminacion'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
